# Generated by Django 6.0.1 on 2026-01-09 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-visit_date']},
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bp_diastolic',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='bp_systolic',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='head_circumference_cm',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='temperature_c',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='visit',
            name='assessment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='chief_complaint',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='visit',
            name='history_of_present_illness',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='physical_exam',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='plan',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('FOLLOW_UP', 'Follow-up')], default='CONSULTATION', max_length=20),
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('bp_systolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bp_diastolic', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('heart_rate_bpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('respiratory_rate_rpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('oxygen_saturation_pct', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('head_circumference_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'ordering': ['-measured_at'],
            },
        ),
    ]
