# Generated by Django 5.1.4 on 2026-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_clinic_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_name',
            field=models.CharField(blank=True, help_text="Custom name for documents (e.g., 'Dr MUKWAMU B. Justin'). If blank, uses first/last name.", max_length=150),
        ),
    ]
