# Generated by Django 5.1.4 on 2026-01-19 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_add_french_fields'),
        ('prescriptions', '0002_alter_medication_options_alter_prescription_options_and_more'),
    ]

    operations = [
    ]
