# Generated by Django 5.1.4 on 2026-01-21 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_backfill_patient_code'),
        ('prescriptions', '0003_merge_20260119_2057'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to='visits.visit'),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplate',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='prescriptiontemplate',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
