# Generated by Django 5.1.4 on 2026-01-21 23:08

from django.db import migrations


def populate_patient_from_visit(apps, schema_editor):
    """Populate patient field from visit.patient for existing prescriptions."""
    Prescription = apps.get_model('prescriptions', 'Prescription')
    for prescription in Prescription.objects.filter(patient__isnull=True, visit__isnull=False):
        prescription.patient = prescription.visit.patient
        prescription.save()


def reverse_populate(apps, schema_editor):
    """Reverse: no action needed as patient will be dropped."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_add_patient_to_prescription'),
    ]

    operations = [
        migrations.RunPython(populate_patient_from_visit, reverse_populate),
    ]
