# Generated by Django 6.0.1 on 2026-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
