# Generated by Django 6.0.1 on 2026-01-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_backfill_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
